### PR TITLE
Hacktoberfest2020commit

### PR DESCRIPTION
**Pull request by Chia2712**
This is a commit from a GitHub coding learner. I have created two different commits and hence, have sent you a pull request. Thank you.

### CODE REVIEW

**Review by AbhishekMaira10 — CHANGES_REQUESTED** [review]
delete the .DS_Store files and try to push changes again. Thank you for contributing

**Comment by Chia2712** [comment]
From where should I do so?

**Comment by AbhishekMaira10** [comment]
In your version of the repository delete the .DS_store files from the profiles, scripts folder, and wherever you spot it.
Commit changes and make a pull request again

**Comment by Chia2712** [comment]
> In your version of the repository delete the .DS_store files from the profiles, scripts folder, and wherever you spot it.
> Commit changes and make a pull request again

It is not showing any such file in the folders.

**Comment by AbhishekMaira10** [comment]
ok, I see what happened. You haven't pulled the changes made to the repository since the time you forked it. Just use the command git pull, delete the files and push the changes

**Comment by Chia2712** [comment]
> ok, I see what happened. You haven't pulled the changes made to the repository since the time you forked it. Just use the command git pull, delete the files and push the changes

I am typing git pull but it is showing that I need to specify the branch I want to merge with. So what will be the code in this case? I am so sorry to disturb you but I am new to this and trying my best to understand the situation.

**Comment by AbhishekMaira10** [comment]
Ya np you can always delete the repository and fork it again, add the changes. You don't have to create a separate branch. You can do it in the main branch itself

**Comment by Chia2712** [comment]
so should I add the files from the option given above on the site, after forking it again?

**Comment by AbhishekMaira10** [comment]
yes

**Pull request closed without merging**
